name: Lint

on:
  push:
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run go fmt
        run: |
          fmtres=$(gofmt -l .)
          if [ -n "$fmtres" ]; then
            echo "The following files are not formatted:"
            echo "$fmtres"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./... 